export interface QuranChapter {
  number: number;
  nameDutch: string;
  nameTurkish: string;
  ayatCount: number;
}

export const quranChapters: QuranChapter[] = [
  { number: 1, nameDutch: "Al-Fatihah (De Opening)", nameTurkish: "Fâtiha Sûresi", ayatCount: 7 },
  { number: 2, nameDutch: "Al-Baqarah (De Koe)", nameTurkish: "Bakara Sûresi", ayatCount: 286 },
  { number: 3, nameDutch: "Al-Imran (De Familie van Imran)", nameTurkish: "Âl-i İmrân Sûresi", ayatCount: 200 },
  { number: 4, nameDutch: "An-Nisa (De Vrouwen)", nameTurkish: "Nisâ Sûresi", ayatCount: 176 },
  { number: 5, nameDutch: "Al-Ma'idah (De Tafel)", nameTurkish: "Mâide Sûresi", ayatCount: 120 },
  { number: 6, nameDutch: "Al-An'am (Het Vee)", nameTurkish: "En'âm Sûresi", ayatCount: 165 },
  { number: 7, nameDutch: "Al-A'raf (De Kantelen)", nameTurkish: "A'râf Sûresi", ayatCount: 206 },
  { number: 8, nameDutch: "Al-Anfal (De Oorlogsbuit)", nameTurkish: "Enfâl Sûresi", ayatCount: 75 },
  { number: 9, nameDutch: "At-Tawbah (Het Berouw)", nameTurkish: "Tevbe Sûresi", ayatCount: 129 },
  { number: 10, nameDutch: "Yunus (Jonas)", nameTurkish: "Yûnus Sûresi", ayatCount: 109 },
  { number: 11, nameDutch: "Hud (Hud)", nameTurkish: "Hûd Sûresi", ayatCount: 123 },
  { number: 12, nameDutch: "Yusuf (Jozef)", nameTurkish: "Yûsuf Sûresi", ayatCount: 111 },
  { number: 13, nameDutch: "Ar-Ra'd (De Donder)", nameTurkish: "Ra'd Sûresi", ayatCount: 43 },
  { number: 14, nameDutch: "Ibrahim (Abraham)", nameTurkish: "İbrâhîm Sûresi", ayatCount: 52 },
  { number: 15, nameDutch: "Al-Hijr (Het Rotsdal)", nameTurkish: "Hicr Sûresi", ayatCount: 99 },
  { number: 16, nameDutch: "An-Nahl (De Bijen)", nameTurkish: "Nahl Sûresi", ayatCount: 128 },
  { number: 17, nameDutch: "Al-Isra (De Nachtreis)", nameTurkish: "İsrâ Sûresi", ayatCount: 111 },
  { number: 18, nameDutch: "Al-Kahf (De Spelonk)", nameTurkish: "Kehf Sûresi", ayatCount: 110 },
  { number: 19, nameDutch: "Maryam (Maria)", nameTurkish: "Meryem Sûresi", ayatCount: 98 },
  { number: 20, nameDutch: "Ta Ha (Ta Ha)", nameTurkish: "Tâhâ Sûresi", ayatCount: 135 },
  { number: 21, nameDutch: "Al-Anbiya (De Profeten)", nameTurkish: "Enbiyâ Sûresi", ayatCount: 112 },
  { number: 22, nameDutch: "Al-Hajj (De Bedevaart)", nameTurkish: "Hac Sûresi", ayatCount: 78 },
  { number: 23, nameDutch: "Al-Mu'minun (De Gelovigen)", nameTurkish: "Mü'minûn Sûresi", ayatCount: 118 },
  { number: 24, nameDutch: "An-Nur (Het Licht)", nameTurkish: "Nûr Sûresi", ayatCount: 64 },
  { number: 25, nameDutch: "Al-Furqan (De Onderscheiding)", nameTurkish: "Furkân Sûresi", ayatCount: 77 },
  { number: 26, nameDutch: "Ash-Shu'ara (De Dichters)", nameTurkish: "Şuarâ Sûresi", ayatCount: 227 },
  { number: 27, nameDutch: "An-Naml (De Mieren)", nameTurkish: "Neml Sûresi", ayatCount: 93 },
  { number: 28, nameDutch: "Al-Qasas (De Vertelling)", nameTurkish: "Kasas Sûresi", ayatCount: 88 },
  { number: 29, nameDutch: "Al-'Ankabut (De Spin)", nameTurkish: "Ankebût Sûresi", ayatCount: 69 },
  { number: 30, nameDutch: "Ar-Rum (De Romeinen)", nameTurkish: "Rûm Sûresi", ayatCount: 60 },
  { number: 31, nameDutch: "Luqman (Luqman)", nameTurkish: "Lokmân Sûresi", ayatCount: 34 },
  { number: 32, nameDutch: "As-Sajdah (De Aanbidding)", nameTurkish: "Secde Sûresi", ayatCount: 30 },
  { number: 33, nameDutch: "Al-Ahzab (De Bondgenoten)", nameTurkish: "Ahzâb Sûresi", ayatCount: 73 },
  { number: 34, nameDutch: "Saba (Saba)", nameTurkish: "Sebe' Sûresi", ayatCount: 54 },
  { number: 35, nameDutch: "Fatir (De Schepper)", nameTurkish: "Fâtır Sûresi", ayatCount: 45 },
  { number: 36, nameDutch: "Ya Sin (Ya Sin)", nameTurkish: "Yâsîn Sûresi", ayatCount: 83 },
  { number: 37, nameDutch: "As-Saffat (In Rijen Geklasseerden)", nameTurkish: "Sâffât Sûresi", ayatCount: 182 },
  { number: 38, nameDutch: "Sad (Sad)", nameTurkish: "Sâd Sûresi", ayatCount: 88 },
  { number: 39, nameDutch: "Az-Zumar (De Drommen)", nameTurkish: "Zümer Sûresi", ayatCount: 75 },
  { number: 40, nameDutch: "Ghafir (De Vergevensgezinde)", nameTurkish: "Mü'min Sûresi", ayatCount: 85 },
  { number: 41, nameDutch: "Fussilat (Gedetailleerd)", nameTurkish: "Fussilet Sûresi", ayatCount: 54 },
  { number: 42, nameDutch: "Ash-Shura (De Consultatie)", nameTurkish: "Şûrâ Sûresi", ayatCount: 53 },
  { number: 43, nameDutch: "Az-Zukhruf (De Versiering)", nameTurkish: "Zuhruf Sûresi", ayatCount: 89 },
  { number: 44, nameDutch: "Ad-Dukhan (De Rook)", nameTurkish: "Duhân Sûresi", ayatCount: 59 },
  { number: 45, nameDutch: "Al-Jathiyah (De Knielende)", nameTurkish: "Câsiye Sûresi", ayatCount: 37 },
  { number: 46, nameDutch: "Al-Ahqaf (De Zandduinen)", nameTurkish: "Ahkâf Sûresi", ayatCount: 35 },
  { number: 47, nameDutch: "Muhammad (Mohammed)", nameTurkish: "Muhammed Sûresi", ayatCount: 38 },
  { number: 48, nameDutch: "Al-Fath (De Overwinning)", nameTurkish: "Fetih Sûresi", ayatCount: 29 },
  { number: 49, nameDutch: "Al-Hujurat (De Binnenvertrekken)", nameTurkish: "Hucurât Sûresi", ayatCount: 18 },
  { number: 50, nameDutch: "Qaf (Qaf)", nameTurkish: "Kâf Sûresi", ayatCount: 45 },
  { number: 51, nameDutch: "Ad-Dhariyat (De Winden)", nameTurkish: "Zâriyât Sûresi", ayatCount: 60 },
  { number: 52, nameDutch: "At-Tur (De Berg)", nameTurkish: "Tûr Sûresi", ayatCount: 49 },
  { number: 53, nameDutch: "An-Najm (De Ster)", nameTurkish: "Necm Sûresi", ayatCount: 62 },
  { number: 54, nameDutch: "Al-Qamar (De Maan)", nameTurkish: "Kamer Sûresi", ayatCount: 55 },
  { number: 55, nameDutch: "Ar-Rahman (De Barmhartige)", nameTurkish: "Rahmân Sûresi", ayatCount: 78 },
  { number: 56, nameDutch: "Al-Waqi'ah (De Onoverkomelijke Gebeurtenis)", nameTurkish: "Vâkıa Sûresi", ayatCount: 96 },
  { number: 57, nameDutch: "Al-Hadid (Het IJzer)", nameTurkish: "Hadîd Sûresi", ayatCount: 29 },
  { number: 58, nameDutch: "Al-Mujadilah (De Pleitende Vrouw)", nameTurkish: "Mücâdele Sûresi", ayatCount: 22 },
  { number: 59, nameDutch: "Al-Hashr (De Verbanning)", nameTurkish: "Haşr Sûresi", ayatCount: 24 },
  { number: 60, nameDutch: "Al-Mumtahanah (De Gekeurde Vrouw)", nameTurkish: "Mümtehine Sûresi", ayatCount: 13 },
  { number: 61, nameDutch: "As-Saff (De Rijen)", nameTurkish: "Saff Sûresi", ayatCount: 14 },
  { number: 62, nameDutch: "Al-Jumu'ah (De Vrijdag)", nameTurkish: "Cuma Sûresi", ayatCount: 11 },
  { number: 63, nameDutch: "Al-Munafiqun (De Huichelaars)", nameTurkish: "Münâfikûn Sûresi", ayatCount: 11 },
  { number: 64, nameDutch: "At-Taghabun (De Wederzijdse Winst en Verlies)", nameTurkish: "Tegâbün Sûresi", ayatCount: 18 },
  { number: 65, nameDutch: "At-Talaq (De Echtscheiding)", nameTurkish: "Talâk Sûresi", ayatCount: 12 },
  { number: 66, nameDutch: "At-Tahrim (De Verbieding)", nameTurkish: "Tahrîm Sûresi", ayatCount: 12 },
  { number: 67, nameDutch: "Al-Mulk (Het Heerschappij)", nameTurkish: "Mülk Sûresi", ayatCount: 30 },
  { number: 68, nameDutch: "Al-Qalam (De Pen)", nameTurkish: "Kalem Sûresi", ayatCount: 52 },
  { number: 69, nameDutch: "Al-Haqqah (De Onvermijdelijke Waarheid)", nameTurkish: "Hâkka Sûresi", ayatCount: 52 },
  { number: 70, nameDutch: "Al-Ma'arij (De Stijgende Trappen)", nameTurkish: "Meâric Sûresi", ayatCount: 44 },
  { number: 71, nameDutch: "Nuh (Noach)", nameTurkish: "Nûh Sûresi", ayatCount: 28 },
  { number: 72, nameDutch: "Al-Jinn (De Djinn)", nameTurkish: "Cin Sûresi", ayatCount: 28 },
  { number: 73, nameDutch: "Al-Muzzammil (De Omwikkelde)", nameTurkish: "Müzzemmil Sûresi", ayatCount: 20 },
  { number: 74, nameDutch: "Al-Muddaththir (De Bekleedde)", nameTurkish: "Müddessir Sûresi", ayatCount: 56 },
  { number: 75, nameDutch: "Al-Qiyamah (De Opstanding)", nameTurkish: "Kıyâme Sûresi", ayatCount: 40 },
  { number: 76, nameDutch: "Al-Insan (De Mens)", nameTurkish: "İnsân Sûresi", ayatCount: 31 },
  { number: 77, nameDutch: "Al-Mursalat (De Uitgezondenen)", nameTurkish: "Mürselât Sûresi", ayatCount: 50 },
  { number: 78, nameDutch: "An-Naba (Het Nieuws)", nameTurkish: "Nebe Sûresi", ayatCount: 40 },
  { number: 79, nameDutch: "An-Nazi'at (De Uittrekkenden)", nameTurkish: "Nâziât Sûresi", ayatCount: 46 },
  { number: 80, nameDutch: "'Abasa (Hij Fronste)", nameTurkish: "Abese Sûresi", ayatCount: 42 },
  { number: 81, nameDutch: "At-Takwir (Het Opvouwen)", nameTurkish: "Tekvîr Sûresi", ayatCount: 29 },
  { number: 82, nameDutch: "Al-Infitar (De Splijting)", nameTurkish: "İnfitâr Sûresi", ayatCount: 19 },
  { number: 83, nameDutch: "Al-Mutaffifin (De Fraudeurs)", nameTurkish: "Mutaffifîn Sûresi", ayatCount: 36 },
  { number: 84, nameDutch: "Al-Inshiqaq (De Scheuring)", nameTurkish: "İnşikâk Sûresi", ayatCount: 25 },
  { number: 85, nameDutch: "Al-Buruj (De Sterrenbeelden)", nameTurkish: "Bürûc Sûresi", ayatCount: 22 },
  { number: 86, nameDutch: "At-Tariq (De Nachtelijke Bezoeker)", nameTurkish: "Târık Sûresi", ayatCount: 17 },
  { number: 87, nameDutch: "Al-A'la (De Allerhoogste)", nameTurkish: "A'lâ Sûresi", ayatCount: 19 },
  { number: 88, nameDutch: "Al-Ghashiyah (De Overweldigende Gebeurtenis)", nameTurkish: "Gâşiye Sûresi", ayatCount: 26 },
  { number: 89, nameDutch: "Al-Fajr (De Dageraad)", nameTurkish: "Fecr Sûresi", ayatCount: 30 },
  { number: 90, nameDutch: "Al-Balad (De Stad)", nameTurkish: "Beled Sûresi", ayatCount: 20 },
  { number: 91, nameDutch: "Ash-Shams (De Zon)", nameTurkish: "Şems Sûresi", ayatCount: 15 },
  { number: 92, nameDutch: "Al-Lail (De Nacht)", nameTurkish: "Leyl Sûresi", ayatCount: 21 },
  { number: 93, nameDutch: "Ad-Duha (De Ochtendglorie)", nameTurkish: "Duhâ Sûresi", ayatCount: 11 },
  { number: 94, nameDutch: "Ash-Sharh (De Verruiming)", nameTurkish: "İnşirâh Sûresi", ayatCount: 8 },
  { number: 95, nameDutch: "At-Tin (De Vijg)", nameTurkish: "Tîn Sûresi", ayatCount: 8 },
  { number: 96, nameDutch: "Al-'Alaq (De Bloedklomp)", nameTurkish: "Alak Sûresi", ayatCount: 19 },
  { number: 97, nameDutch: "Al-Qadr (De Waardigheid)", nameTurkish: "Kadir Sûresi", ayatCount: 5 },
  { number: 98, nameDutch: "Al-Bayyinah (Het Duidelijke Bewijs)", nameTurkish: "Beyyine Sûresi", ayatCount: 8 },
  { number: 99, nameDutch: "Az-Zalzalah (De Beving)", nameTurkish: "Zilzâl Sûresi", ayatCount: 8 },
  { number: 100, nameDutch: "Al-'Adiyat (De Rennenden)", nameTurkish: "Âdiyât Sûresi", ayatCount: 11 },
  { number: 101, nameDutch: "Al-Qari'ah (De Kletterende Slag)", nameTurkish: "Kâria Sûresi", ayatCount: 11 },
  { number: 102, nameDutch: "At-Takathur (De Wedijver om Vermeerdering)", nameTurkish: "Tekâsür Sûresi", ayatCount: 8 },
  { number: 103, nameDutch: "Al-'Asr (De Tijd)", nameTurkish: "Asr Sûresi", ayatCount: 3 },
  { number: 104, nameDutch: "Al-Humazah (De Lasteraar)", nameTurkish: "Hümeze Sûresi", ayatCount: 9 },
  { number: 105, nameDutch: "Al-Fil (De Olifant)", nameTurkish: "Fîl Sûresi", ayatCount: 5 },
  { number: 106, nameDutch: "Quraysh (Koreisj)", nameTurkish: "Kureyş Sûresi", ayatCount: 4 },
  { number: 107, nameDutch: "Al-Ma'un (De Kleine Vriendelijkheden)", nameTurkish: "Mâûn Sûresi", ayatCount: 7 },
  { number: 108, nameDutch: "Al-Kawthar (De Overvloed)", nameTurkish: "Kevser Sûresi", ayatCount: 3 },
  { number: 109, nameDutch: "Al-Kafirun (De Ongelovigen)", nameTurkish: "Kâfirûn Sûresi", ayatCount: 6 },
  { number: 110, nameDutch: "An-Nasr (De Hulp)", nameTurkish: "Nasr Sûresi", ayatCount: 3 },
  { number: 111, nameDutch: "Al-Masad (De Palmvezels)", nameTurkish: "Tebbet Sûresi", ayatCount: 5 },
  { number: 112, nameDutch: "Al-Ikhlas (De Zuiverheid)", nameTurkish: "İhlâs Sûresi", ayatCount: 4 },
  { number: 113, nameDutch: "Al-Falaq (De Dageraad)", nameTurkish: "Felak Sûresi", ayatCount: 5 },
  { number: 114, nameDutch: "An-Nas (De Mensheid)", nameTurkish: "Nâs Sûresi", ayatCount: 6 },
];
